package cn.iocoder.yudao.module.erp.controller.admin.finance.prereceipt;

import org.springframework.web.bind.annotation.*;
import javax.annotation.Resource;
import org.springframework.validation.annotation.Validated;
import org.springframework.security.access.prepost.PreAuthorize;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Operation;

import javax.validation.constraints.*;
import javax.validation.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.IOException;

import cn.iocoder.yudao.framework.common.pojo.PageParam;
import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.common.pojo.CommonResult;
import cn.iocoder.yudao.framework.common.util.object.BeanUtils;
import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success;

import cn.iocoder.yudao.framework.excel.core.util.ExcelUtils;

import cn.iocoder.yudao.framework.apilog.core.annotation.ApiAccessLog;
import static cn.iocoder.yudao.framework.apilog.core.enums.OperateTypeEnum.*;

import cn.iocoder.yudao.module.erp.controller.admin.finance.prereceipt.vo.*;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.prereceipt.ErpFinancePrereceiptDO;
import cn.iocoder.yudao.module.erp.dal.dataobject.sale.ErpCustomerDO;
import cn.iocoder.yudao.module.erp.service.finance.prereceipt.ErpFinancePrereceiptService;
import cn.iocoder.yudao.module.erp.service.sale.ErpCustomerService;
import cn.hutool.core.collection.CollUtil;
import cn.iocoder.yudao.framework.common.util.collection.MapUtils;
import static cn.iocoder.yudao.framework.common.util.collection.CollectionUtils.convertSet;

@Tag(name = "管理后台 - 预收款")
@RestController
@RequestMapping("/erp/finance-prereceipt")
@Validated
public class ErpFinancePrereceiptController {

    @Resource
    private ErpFinancePrereceiptService financePrereceiptService;

    @Resource
    private ErpCustomerService customerService;

    @PostMapping("/create")
    @Operation(summary = "创建预收款")
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:create')")
    public CommonResult<Long> createFinancePrereceipt(@Valid @RequestBody ErpFinancePrereceiptSaveReqVO createReqVO) {
        return success(financePrereceiptService.createFinancePrereceipt(createReqVO));
    }

    @PutMapping("/update")
    @Operation(summary = "更新预收款")
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:update')")
    public CommonResult<Boolean> updateFinancePrereceipt(@Valid @RequestBody ErpFinancePrereceiptSaveReqVO updateReqVO) {
        financePrereceiptService.updateFinancePrereceipt(updateReqVO);
        return success(true);
    }

    @DeleteMapping("/delete")
    @Operation(summary = "删除预收款")
    @Parameter(name = "id", description = "编号", required = true)
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:delete')")
    public CommonResult<Boolean> deleteFinancePrereceipt(@RequestParam("id") Long id) {
        financePrereceiptService.deleteFinancePrereceipt(id);
        return success(true);
    }

    @DeleteMapping("/delete-list")
    @Parameter(name = "ids", description = "编号", required = true)
    @Operation(summary = "批量删除预收款")
                @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:delete')")
    public CommonResult<Boolean> deleteFinancePrereceiptList(@RequestParam("ids") List<Long> ids) {
        financePrereceiptService.deleteFinancePrereceiptListByIds(ids);
        return success(true);
    }

    @GetMapping("/get")
    @Operation(summary = "获得预收款")
    @Parameter(name = "id", description = "编号", required = true, example = "1024")
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:query')")
    public CommonResult<ErpFinancePrereceiptRespVO> getFinancePrereceipt(@RequestParam("id") Long id) {
        ErpFinancePrereceiptDO financePrereceipt = financePrereceiptService.getFinancePrereceipt(id);
        ErpFinancePrereceiptRespVO respVO = BeanUtils.toBean(financePrereceipt, ErpFinancePrereceiptRespVO.class);
        // 填充客户名称
        if (respVO != null && respVO.getCustomerId() != null) {
            ErpCustomerDO customer = customerService.getCustomer(respVO.getCustomerId());
            if (customer != null) {
                respVO.setCustomerName(customer.getName());
            }
        }
        // 设置是否自动生成
        if (respVO != null) {
            respVO.setAutoGenerated(isAutoGenerated(respVO.getOrderId(), respVO.getRemark()));
        }
        return success(respVO);
    }

    @GetMapping("/page")
    @Operation(summary = "获得预收款分页")
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:query')")
    public CommonResult<PageResult<ErpFinancePrereceiptRespVO>> getFinancePrereceiptPage(@Valid ErpFinancePrereceiptPageReqVO pageReqVO) {
        PageResult<ErpFinancePrereceiptDO> pageResult = financePrereceiptService.getFinancePrereceiptPage(pageReqVO);
        // 获取客户信息
        Set<Long> customerIds = convertSet(pageResult.getList(), ErpFinancePrereceiptDO::getCustomerId, 
                prereceipt -> prereceipt.getCustomerId() != null);
        Map<Long, ErpCustomerDO> customerMap = CollUtil.isEmpty(customerIds) ? Collections.emptyMap() :
                customerService.getCustomerMap(customerIds);
        // 转换为 VO 并填充客户名称
        return success(BeanUtils.toBean(pageResult, ErpFinancePrereceiptRespVO.class, prereceipt -> {
            MapUtils.findAndThen(customerMap, prereceipt.getCustomerId(), customer -> {
                prereceipt.setCustomerName(customer.getName());
            });
            // 设置是否自动生成
            prereceipt.setAutoGenerated(isAutoGenerated(prereceipt.getOrderId(), prereceipt.getRemark()));
        }));
    }

    @GetMapping("/export-excel")
    @Operation(summary = "导出预收款 Excel")
    @PreAuthorize("@ss.hasPermission('erp:finance-prereceipt:export')")
    @ApiAccessLog(operateType = EXPORT)
    public void exportFinancePrereceiptExcel(@Valid ErpFinancePrereceiptPageReqVO pageReqVO,
              HttpServletResponse response) throws IOException {
        pageReqVO.setPageSize(PageParam.PAGE_SIZE_NONE);
        List<ErpFinancePrereceiptDO> list = financePrereceiptService.getFinancePrereceiptPage(pageReqVO).getList();
        // 获取客户信息
        Set<Long> customerIds = convertSet(list, ErpFinancePrereceiptDO::getCustomerId, 
                prereceipt -> prereceipt.getCustomerId() != null);
        Map<Long, ErpCustomerDO> customerMap = CollUtil.isEmpty(customerIds) ? Collections.emptyMap() :
                customerService.getCustomerMap(customerIds);
        // 转换为 VO 并填充客户名称
        List<ErpFinancePrereceiptRespVO> respList = BeanUtils.toBean(list, ErpFinancePrereceiptRespVO.class, prereceipt -> {
            MapUtils.findAndThen(customerMap, prereceipt.getCustomerId(), customer -> {
                prereceipt.setCustomerName(customer.getName());
            });
            // 设置是否自动生成
            prereceipt.setAutoGenerated(isAutoGenerated(prereceipt.getOrderId(), prereceipt.getRemark()));
        });
        // 导出 Excel
        ExcelUtils.write(response, "预收款.xls", "数据", ErpFinancePrereceiptRespVO.class, respList);
    }

    /**
     * 判断是否自动生成
     * 如果 orderId 不为空且 remark 包含"自动生成"，则认为是自动生成的
     */
    private Boolean isAutoGenerated(Long orderId, String remark) {
        if (orderId != null && remark != null && remark.contains("自动生成")) {
            return true;
        }
        return false;
    }

}