package cn.iocoder.yudao.module.erp.controller.admin.finance.prepayment;

import org.springframework.web.bind.annotation.*;
import javax.annotation.Resource;
import org.springframework.validation.annotation.Validated;
import org.springframework.security.access.prepost.PreAuthorize;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Operation;

import javax.validation.constraints.*;
import javax.validation.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.IOException;

import cn.iocoder.yudao.framework.common.pojo.PageParam;
import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.common.pojo.CommonResult;
import cn.iocoder.yudao.framework.common.util.object.BeanUtils;
import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success;

import cn.iocoder.yudao.framework.excel.core.util.ExcelUtils;

import cn.iocoder.yudao.framework.apilog.core.annotation.ApiAccessLog;
import static cn.iocoder.yudao.framework.apilog.core.enums.OperateTypeEnum.*;

import cn.iocoder.yudao.module.erp.controller.admin.finance.prepayment.vo.*;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.prepayment.ErpFinancePrepaymentDO;
import cn.iocoder.yudao.module.erp.dal.dataobject.purchase.ErpSupplierDO;
import cn.iocoder.yudao.module.erp.service.prepayment.ErpFinancePrepaymentService;
import cn.iocoder.yudao.module.erp.service.purchase.ErpSupplierService;
import cn.hutool.core.collection.CollUtil;
import cn.iocoder.yudao.framework.common.util.collection.MapUtils;
import static cn.iocoder.yudao.framework.common.util.collection.CollectionUtils.convertSet;

@Tag(name = "管理后台 - 预付款")
@RestController
@RequestMapping("/erp/finance-prepayment")
@Validated
public class ErpFinancePrepaymentController {

    @Resource
    private ErpFinancePrepaymentService financePrepaymentService;

    @Resource
    private ErpSupplierService supplierService;

    @PostMapping("/create")
    @Operation(summary = "创建预付款")
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:create')")
    public CommonResult<Long> createFinancePrepayment(@Valid @RequestBody ErpFinancePrepaymentSaveReqVO createReqVO) {
        return success(financePrepaymentService.createFinancePrepayment(createReqVO));
    }

    @PutMapping("/update")
    @Operation(summary = "更新预付款")
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:update')")
    public CommonResult<Boolean> updateFinancePrepayment(@Valid @RequestBody ErpFinancePrepaymentSaveReqVO updateReqVO) {
        financePrepaymentService.updateFinancePrepayment(updateReqVO);
        return success(true);
    }

    @DeleteMapping("/delete")
    @Operation(summary = "删除预付款")
    @Parameter(name = "id", description = "编号", required = true)
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:delete')")
    public CommonResult<Boolean> deleteFinancePrepayment(@RequestParam("id") Long id) {
        financePrepaymentService.deleteFinancePrepayment(id);
        return success(true);
    }

    @DeleteMapping("/delete-list")
    @Parameter(name = "ids", description = "编号", required = true)
    @Operation(summary = "批量删除预付款")
                @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:delete')")
    public CommonResult<Boolean> deleteFinancePrepaymentList(@RequestParam("ids") List<Long> ids) {
        financePrepaymentService.deleteFinancePrepaymentListByIds(ids);
        return success(true);
    }

    @GetMapping("/get")
    @Operation(summary = "获得预付款")
    @Parameter(name = "id", description = "编号", required = true, example = "1024")
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:query')")
    public CommonResult<ErpFinancePrepaymentRespVO> getFinancePrepayment(@RequestParam("id") Long id) {
        ErpFinancePrepaymentDO financePrepayment = financePrepaymentService.getFinancePrepayment(id);
        ErpFinancePrepaymentRespVO respVO = BeanUtils.toBean(financePrepayment, ErpFinancePrepaymentRespVO.class);
        // 填充供应商名称
        if (respVO != null && respVO.getSupplierId() != null) {
            ErpSupplierDO supplier = supplierService.getSupplier(respVO.getSupplierId());
            if (supplier != null) {
                respVO.setSupplierName(supplier.getName());
            }
        }
        // 设置是否自动生成
        if (respVO != null) {
            respVO.setAutoGenerated(isAutoGenerated(respVO.getOrderId(), respVO.getRemark()));
        }
        return success(respVO);
    }

    @GetMapping("/page")
    @Operation(summary = "获得预付款分页")
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:query')")
    public CommonResult<PageResult<ErpFinancePrepaymentRespVO>> getFinancePrepaymentPage(@Valid ErpFinancePrepaymentPageReqVO pageReqVO) {
        PageResult<ErpFinancePrepaymentDO> pageResult = financePrepaymentService.getFinancePrepaymentPage(pageReqVO);
        // 获取供应商信息
        Set<Long> supplierIds = convertSet(pageResult.getList(), ErpFinancePrepaymentDO::getSupplierId, 
                prepayment -> prepayment.getSupplierId() != null);
        Map<Long, ErpSupplierDO> supplierMap = CollUtil.isEmpty(supplierIds) ? Collections.emptyMap() :
                supplierService.getSupplierMap(supplierIds);
        // 转换为 VO 并填充供应商名称
        return success(BeanUtils.toBean(pageResult, ErpFinancePrepaymentRespVO.class, prepayment -> {
            MapUtils.findAndThen(supplierMap, prepayment.getSupplierId(), supplier -> {
                prepayment.setSupplierName(supplier.getName());
            });
            // 设置是否自动生成
            prepayment.setAutoGenerated(isAutoGenerated(prepayment.getOrderId(), prepayment.getRemark()));
        }));
    }

    @GetMapping("/export-excel")
    @Operation(summary = "导出预付款 Excel")
    @PreAuthorize("@ss.hasPermission('erp:finance-prepayment:export')")
    @ApiAccessLog(operateType = EXPORT)
    public void exportFinancePrepaymentExcel(@Valid ErpFinancePrepaymentPageReqVO pageReqVO,
              HttpServletResponse response) throws IOException {
        pageReqVO.setPageSize(PageParam.PAGE_SIZE_NONE);
        List<ErpFinancePrepaymentDO> list = financePrepaymentService.getFinancePrepaymentPage(pageReqVO).getList();
        // 获取供应商信息
        Set<Long> supplierIds = convertSet(list, ErpFinancePrepaymentDO::getSupplierId, 
                prepayment -> prepayment.getSupplierId() != null);
        Map<Long, ErpSupplierDO> supplierMap = CollUtil.isEmpty(supplierIds) ? Collections.emptyMap() :
                supplierService.getSupplierMap(supplierIds);
        // 转换为 VO 并填充供应商名称
        List<ErpFinancePrepaymentRespVO> respList = BeanUtils.toBean(list, ErpFinancePrepaymentRespVO.class, prepayment -> {
            MapUtils.findAndThen(supplierMap, prepayment.getSupplierId(), supplier -> {
                prepayment.setSupplierName(supplier.getName());
            });
            // 设置是否自动生成
            prepayment.setAutoGenerated(isAutoGenerated(prepayment.getOrderId(), prepayment.getRemark()));
        });
        // 导出 Excel
        ExcelUtils.write(response, "预付款.xls", "数据", ErpFinancePrepaymentRespVO.class, respList);
    }

    /**
     * 判断是否自动生成
     * 如果 orderId 不为空且 remark 包含"自动生成"，则认为是自动生成的
     */
    private Boolean isAutoGenerated(Long orderId, String remark) {
        if (orderId != null && remark != null && remark.contains("自动生成")) {
            return true;
        }
        return false;
    }

}